name: Deployment Ex 1
on: push
jobs:
  Lint_job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

  Test_job:
    runs-on: ubuntu-latest
    needs: Lint_job
    steps: 
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test

  Deploy_job:
    runs-on: ubuntu-latest
    needs: Test_job
    steps: 
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy code
        run: echo "Deploying..."